### ISSUE TITLE
"expanded" bool is never saved

### ISSUE THREAD

**Issue by kobligo** [dimmpixeye/InspectorFoldoutGroup#4]
You've probably moved on and abandoned this project, but I'm reporting this issue anyway because it makes the "InspectorFoldoutGroup" scripts unusable -- and I would very much like to use them for my game project:

The "expanded" bool that defines the folded state of a Foldout group is never saved.
When you deselect an object that uses the Foldout groups, or when you simply run the game in the editor, the Foldout groups are immediately closed. All of them.
Of course normally you would expect them to remember their last state, so that you don't have to reopen them by hand all the time.
(I'm on Unity 2018.3.6f1 btw.)

**Comment by PixeyeHQ** [comment]
@kobligo hey! Thanks for the feedback, no, it's not abandoned, I use it as a part of my ecs project and already updated heavily there. Will add changes in this project as well. 

Thanks again for your interest!

**Comment by kobligo** [comment]
Wow, that was unexpected. Thank you. I'm excited to see how this tool has developed.

**Comment by PixeyeHQ** [comment]
@kobligo  hey :) I've added new version that prevents auto folding groups when the editor is reloaded. Feel free to check and PM if any issues occur.

**Comment by kobligo** [comment]
Since there is no way to PM users on github, I'm putting this here:

The updated scripts are working great so far. Thank you. The only issue I can see right now is that it's putting each variable into its own box when foldEverything is set to true. I don't think that's intentional.

**Comment by PixeyeHQ** [comment]
@kobligo hmm.. ye, I think it will be easy to fix : ) Thanks for the feedback, I'll fix that asap : )
